In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [6]:
df = pd.read_csv(r'C:\Users\SOHAIL SONS TRADERS\Desktop\proj\Stroke-Prediction-Web-Application-main\Dataset\healthcare-dataset-stroke-data.csv')
df.head()

id  gender   age  hypertension  heart_disease ever_married  \
0   9046    Male  67.0             0              1          Yes   
1  51676  Female  61.0             0              0          Yes   
2  31112    Male  80.0             0              1          Yes   
3  60182  Female  49.0             0              0          Yes   
4   1665  Female  79.0             1              0          Yes   

       work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0        Private          Urban             228.69  36.6  formerly smoked   
1  Self-employed          Rural             202.21   NaN     never smoked   
2        Private          Rural             105.92  32.5     never smoked   
3        Private          Urban             171.23  34.4           smokes   
4  Self-employed          Rural             174.12  24.0     never smoked   

   stroke  
0       1  
1       1  
2       1  
3       1  
4       1

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   id                 5110 non-null   int64  
 1   gender             5110 non-null   object 
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64  
 4   heart_disease      5110 non-null   int64  
 5   ever_married       5110 non-null   object 
 6   work_type          5110 non-null   object 
 7   Residence_type     5110 non-null   object 
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   object 
 11  stroke             5110 non-null   int64  
dtypes: float64(3), int64(4), object(5)
memory usage: 479.2+ KB


In [8]:
df.isnull().sum()

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

In [9]:
df['bmi'] = df['bmi'].fillna(df['bmi'].mean())

In [10]:
df.drop_duplicates(inplace=True)

In [11]:
df.drop('id',axis=1,inplace=True)

In [12]:
df.head()

gender   age  hypertension  heart_disease ever_married      work_type  \
0    Male  67.0             0              1          Yes        Private   
1  Female  61.0             0              0          Yes  Self-employed   
2    Male  80.0             0              1          Yes        Private   
3  Female  49.0             0              0          Yes        Private   
4  Female  79.0             1              0          Yes  Self-employed   

  Residence_type  avg_glucose_level        bmi   smoking_status  stroke  
0          Urban             228.69  36.600000  formerly smoked       1  
1          Rural             202.21  28.893237     never smoked       1  
2          Rural             105.92  32.500000     never smoked       1  
3          Urban             171.23  34.400000           smokes       1  
4          Rural             174.12  24.000000     never smoked       1

In [13]:
features = df.iloc[:,:-1]
target = df.iloc[:,-1]

In [14]:
cols = features[['gender', 'ever_married', 'work_type', 'Residence_type','smoking_status']]

In [15]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
features['gender'] = le.fit_transform(features['gender'])
features['ever_married'] = le.fit_transform(features['ever_married'])
features['work_type'] = le.fit_transform(features['work_type'])
features['Residence_type'] = le.fit_transform(features['Residence_type'])
features['smoking_status'] = le.fit_transform(features['smoking_status'])

In [16]:
df.head()

gender   age  hypertension  heart_disease ever_married      work_type  \
0    Male  67.0             0              1          Yes        Private   
1  Female  61.0             0              0          Yes  Self-employed   
2    Male  80.0             0              1          Yes        Private   
3  Female  49.0             0              0          Yes        Private   
4  Female  79.0             1              0          Yes  Self-employed   

  Residence_type  avg_glucose_level        bmi   smoking_status  stroke  
0          Urban             228.69  36.600000  formerly smoked       1  
1          Rural             202.21  28.893237     never smoked       1  
2          Rural             105.92  32.500000     never smoked       1  
3          Urban             171.23  34.400000           smokes       1  
4          Rural             174.12  24.000000     never smoked       1

In [17]:
features.head()

gender   age  hypertension  heart_disease  ever_married  work_type  \
0       1  67.0             0              1             1          2   
1       0  61.0             0              0             1          3   
2       1  80.0             0              1             1          2   
3       0  49.0             0              0             1          2   
4       0  79.0             1              0             1          3   

   Residence_type  avg_glucose_level        bmi  smoking_status  
0               1             228.69  36.600000               1  
1               0             202.21  28.893237               2  
2               0             105.92  32.500000               2  
3               1             171.23  34.400000               3  
4               0             174.12  24.000000               2

In [18]:
features.work_type.value_counts()

work_type
2    2925
3     819
4     687
0     657
1      22
Name: count, dtype: int64

In [19]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(features,target,random_state=2,test_size=0.3,stratify=target)

In [20]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(xtrain,ytrain)
ypred = rf.predict(xtest)

In [21]:
train = rf.score(xtrain,ytrain)
test = rf.score(xtest,ytest)

print(f'Training_Acc : {train}\nTesting_Acc : {test}')

Training_Acc : 1.0
Testing_Acc : 0.9504240052185258


In [22]:
from sklearn.metrics import confusion_matrix,classification_report
cm = confusion_matrix(ytest,ypred)
cr = classification_report(ytest,ypred)

print(f'{cm}\n{cr}')

[[1457    1]
 [  75    0]]
              precision    recall  f1-score   support

           0       0.95      1.00      0.97      1458
           1       0.00      0.00      0.00        75

    accuracy                           0.95      1533
   macro avg       0.48      0.50      0.49      1533
weighted avg       0.90      0.95      0.93      1533



In [23]:
pip install imblearn

Note: you may need to restart the kernel to use updated packages.


In [24]:
from imblearn.under_sampling import RandomUnderSampler
rus = RandomUnderSampler()
x_sample,y_sample = rus.fit_resample(features,target)

In [25]:
xtrain,xtest,ytrain,ytest = train_test_split(x_sample,y_sample,random_state=2,test_size=0.3)

In [26]:
rf.fit(xtrain,ytrain)
ypred = rf.predict(xtest)

In [27]:
train = rf.score(x_sample,y_sample)
test = rf.score(xtest,ytest)

print(f'Training_Acc : {train}\nTesting_Acc : {test}')

Training_Acc : 0.9176706827309237
Testing_Acc : 0.7266666666666667


In [28]:
cm = confusion_matrix(ytest,ypred)
cr = classification_report(ytest,ypred)

print(f'{cm}\n{cr}')

[[48 22]
 [19 61]]
              precision    recall  f1-score   support

           0       0.72      0.69      0.70        70
           1       0.73      0.76      0.75        80

    accuracy                           0.73       150
   macro avg       0.73      0.72      0.72       150
weighted avg       0.73      0.73      0.73       150



In [29]:
parameter = {
    'criterion':['gini','entropy'],
    'max_depth':list(range(1,20)),
    'min_samples_leaf':list(range(1,20))
}

In [30]:
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(rf,parameter,verbose=2)
grid.fit(xtrain,ytrain)

Fitting 5 folds for each of 722 candidates, totalling 3610 fits
[CV] END ....criterion=gini, max_depth=1, min_samples_leaf=1; total time=   0.1s
[CV] END ....criterion=gini, max_depth=1, min_samples_leaf=1; total time=   0.1s
[CV] END ....criterion=gini, max_depth=1, min_samples_leaf=1; total time=   0.1s
[CV] END ....criterion=gini, max_depth=1, min_samples_leaf=1; total time=   0.1s
[CV] END ....criterion=gini, max_depth=1, min_samples_leaf=1; total time=   0.1s
[CV] END ....criterion=gini, max_depth=1, min_samples_leaf=2; total time=   0.2s
[CV] END ....criterion=gini, max_depth=1, min_samples_leaf=2; total time=   0.1s
[CV] END ....criterion=gini, max_depth=1, min_samples_leaf=2; total time=   0.1s
[CV] END ....criterion=gini, max_depth=1, min_samples_leaf=2; total time=   0.1s
[CV] END ....criterion=gini, max_depth=1, min_samples_leaf=2; total time=   0.1s
[CV] END ....criterion=gini, max_depth=1, min_samples_leaf=3; total time=   0.1s
[CV] END ....criterion=gini, max_depth=1, min

GridSearchCV(estimator=RandomForestClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                       13, 14, 15, 16, 17, 18, 19],
                         'min_samples_leaf': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
                                              12, 13, 14, 15, 16, 17, 18, 19]},
             verbose=2)

In [31]:
grid.best_estimator_

RandomForestClassifier(max_depth=17, min_samples_leaf=12)

In [32]:
rf = grid.best_estimator_
rf.fit(xtrain,ytrain)
ypred = rf.predict(xtest)

In [33]:
train = rf.score(x_sample,y_sample)
test = rf.score(xtest,ytest)

print(f'Training_Acc : {train}\nTesting_Acc : {test}')

Training_Acc : 0.8012048192771084
Testing_Acc : 0.76


In [34]:
cm = confusion_matrix(ytest,ypred)
cr = classification_report(ytest,ypred)

print(f'{cm}\n{cr}')

[[50 20]
 [16 64]]
              precision    recall  f1-score   support

           0       0.76      0.71      0.74        70
           1       0.76      0.80      0.78        80

    accuracy                           0.76       150
   macro avg       0.76      0.76      0.76       150
weighted avg       0.76      0.76      0.76       150



In [35]:
import pickle
pickle.dump(rf,open('./model.sav', 'wb'))

In [36]:
pickle.load(open('model.sav', 'rb'))

RandomForestClassifier(max_depth=17, min_samples_leaf=12)